#
//  .swiftlint.yml
//  TextSniper
//
//  Created by Lofrumento, Gianluca on 2024-09-30.
//

opt_in_rules:
    - indentation_width
    - explicit_self
    - operator_usage_whitespace

included:
    - TextSniper
